//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/ControlJuego.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlJuego: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlJuego()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlJuego"",
    ""maps"": [
        {
            ""name"": ""ControlesInGame"",
            ""id"": ""fd663fba-a09a-4152-9556-54ddfb09510f"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""Value"",
                    ""id"": ""faf49f59-05c2-4da9-9ad4-21332e49b55d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""a9edd0dd-839a-4a12-aa02-fbd469ce45b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""c614f072-63fd-4985-9059-c5bb4299bfe7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ledge"",
                    ""type"": ""Value"",
                    ""id"": ""75008cd7-1d0b-4101-a23b-1d5c2cd2285b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Climb"",
                    ""type"": ""Value"",
                    ""id"": ""60e204cb-e282-4916-952f-bf78c4ae2883"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Ataque"",
                    ""type"": ""Button"",
                    ""id"": ""26b8ae8d-377f-4e02-baaa-f8784087820b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parry"",
                    ""type"": ""Button"",
                    ""id"": ""f23b1236-e6c9-4ac5-928a-8d7384f43ddd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4eed1fd4-1684-4591-bc89-930ae0fb094d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ba32abfc-e128-400a-908b-3b273c052640"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""faefe881-20bc-4f01-ba4b-16326e072ed0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""119cea59-1f61-4c06-b0eb-4564d51a2699"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""275b6cec-3a8a-49b1-a68a-7182a97c266a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a34bf21-194d-4171-b72e-df96975b5bf1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1d65721f-ea43-4352-befb-59102ad0bce3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""477e1db8-50b8-4e8f-bd98-e722b910cb79"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f5535bf5-6121-4fd1-96f5-50f2cd4719b0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e23b2fac-1348-4e96-863f-67eef3b7d3bb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""72eaae6c-3a8d-4180-ab16-246161521188"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5c9fc383-6738-4108-a3cb-dbf990d1570a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""74ea0f8c-95b5-484b-bf72-4fd35465fc3f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb8f48a8-ea39-4ff3-989d-1aac14297dbb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b6b9613b-7586-4e29-96ee-74f977965c1c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3bde9120-3c6b-4d1e-bd50-5959561ae8fd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6f04ad7e-8bac-4ae2-9c0b-f1658d61447c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""354d2a00-80a0-4dea-bc7f-05f52d28d83b"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ataque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77c1cfcd-4b05-4221-90a6-f168c3e8d60d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38f0989f-fabe-4993-b827-0cd71f4e6d6d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ControlesInMenu"",
            ""id"": ""a861e75a-50c1-4e80-b08d-a684de97df2f"",
            ""actions"": [
                {
                    ""name"": ""NavegarMenu"",
                    ""type"": ""Value"",
                    ""id"": ""9cde9463-bb31-49d1-93be-1e1157e3e07c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Seleccionar"",
                    ""type"": ""Button"",
                    ""id"": ""8a2d992b-60b8-420f-ae18-3993d87b44cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Atras"",
                    ""type"": ""Button"",
                    ""id"": ""f7fbc180-2fc7-4bfa-9704-dfa954f03a36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pestanyas"",
                    ""type"": ""Button"",
                    ""id"": ""890872c3-c7c6-457f-a62b-90ad31e482d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""79ae9432-08c8-4b4f-95ff-da3d03c6041b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e18dc6bb-8eb8-4fac-984f-0cf905a952ca"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d961100e-5888-4dbd-bc89-a10f163e44a0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""23463764-daa1-40c7-8473-fc2fccd0f602"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""06b6e157-c7b5-4f95-97aa-29d8a42dcee6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""FLECHAS"",
                    ""id"": ""ca175c57-f813-4bf0-96ba-854df83bb1f7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""05701532-bb17-4644-86c4-d0ae7bbdd057"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1c91a6d7-5b4c-484a-8f0c-6cb44ea8cd6a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""92b3f162-c4fb-4244-9681-f3fb93475433"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ad15e01f-9384-4326-aea0-59db8abd4504"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavegarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3cab68a6-1cfc-4237-8f28-75ca5cfd6a57"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seleccionar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efe0233a-6ef8-403d-9fbd-ff605fd146e8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seleccionar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""699b9f94-5535-4820-af5d-638a6949fd51"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""306e2173-a8df-4bee-bcdf-b87098fd9a35"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c6dba2e7-3fbc-4979-bb66-01253c1dbb21"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pestanyas"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""70fd740f-af66-4d6e-9e29-90080c9e0527"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pestanyas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9dd21c20-4fcb-48b5-bf3a-442cf19ae963"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pestanyas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ControlesInGame
        m_ControlesInGame = asset.FindActionMap("ControlesInGame", throwIfNotFound: true);
        m_ControlesInGame_Movimiento = m_ControlesInGame.FindAction("Movimiento", throwIfNotFound: true);
        m_ControlesInGame_Saltar = m_ControlesInGame.FindAction("Saltar", throwIfNotFound: true);
        m_ControlesInGame_Dash = m_ControlesInGame.FindAction("Dash", throwIfNotFound: true);
        m_ControlesInGame_Ledge = m_ControlesInGame.FindAction("Ledge", throwIfNotFound: true);
        m_ControlesInGame_Climb = m_ControlesInGame.FindAction("Climb", throwIfNotFound: true);
        m_ControlesInGame_Ataque = m_ControlesInGame.FindAction("Ataque", throwIfNotFound: true);
        m_ControlesInGame_Parry = m_ControlesInGame.FindAction("Parry", throwIfNotFound: true);
        m_ControlesInGame_Interact = m_ControlesInGame.FindAction("Interact", throwIfNotFound: true);
        // ControlesInMenu
        m_ControlesInMenu = asset.FindActionMap("ControlesInMenu", throwIfNotFound: true);
        m_ControlesInMenu_NavegarMenu = m_ControlesInMenu.FindAction("NavegarMenu", throwIfNotFound: true);
        m_ControlesInMenu_Seleccionar = m_ControlesInMenu.FindAction("Seleccionar", throwIfNotFound: true);
        m_ControlesInMenu_Atras = m_ControlesInMenu.FindAction("Atras", throwIfNotFound: true);
        m_ControlesInMenu_Pestanyas = m_ControlesInMenu.FindAction("Pestanyas", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlesInGame
    private readonly InputActionMap m_ControlesInGame;
    private List<IControlesInGameActions> m_ControlesInGameActionsCallbackInterfaces = new List<IControlesInGameActions>();
    private readonly InputAction m_ControlesInGame_Movimiento;
    private readonly InputAction m_ControlesInGame_Saltar;
    private readonly InputAction m_ControlesInGame_Dash;
    private readonly InputAction m_ControlesInGame_Ledge;
    private readonly InputAction m_ControlesInGame_Climb;
    private readonly InputAction m_ControlesInGame_Ataque;
    private readonly InputAction m_ControlesInGame_Parry;
    private readonly InputAction m_ControlesInGame_Interact;
    public struct ControlesInGameActions
    {
        private @ControlJuego m_Wrapper;
        public ControlesInGameActions(@ControlJuego wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimiento => m_Wrapper.m_ControlesInGame_Movimiento;
        public InputAction @Saltar => m_Wrapper.m_ControlesInGame_Saltar;
        public InputAction @Dash => m_Wrapper.m_ControlesInGame_Dash;
        public InputAction @Ledge => m_Wrapper.m_ControlesInGame_Ledge;
        public InputAction @Climb => m_Wrapper.m_ControlesInGame_Climb;
        public InputAction @Ataque => m_Wrapper.m_ControlesInGame_Ataque;
        public InputAction @Parry => m_Wrapper.m_ControlesInGame_Parry;
        public InputAction @Interact => m_Wrapper.m_ControlesInGame_Interact;
        public InputActionMap Get() { return m_Wrapper.m_ControlesInGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlesInGameActions set) { return set.Get(); }
        public void AddCallbacks(IControlesInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Add(instance);
            @Movimiento.started += instance.OnMovimiento;
            @Movimiento.performed += instance.OnMovimiento;
            @Movimiento.canceled += instance.OnMovimiento;
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Ledge.started += instance.OnLedge;
            @Ledge.performed += instance.OnLedge;
            @Ledge.canceled += instance.OnLedge;
            @Climb.started += instance.OnClimb;
            @Climb.performed += instance.OnClimb;
            @Climb.canceled += instance.OnClimb;
            @Ataque.started += instance.OnAtaque;
            @Ataque.performed += instance.OnAtaque;
            @Ataque.canceled += instance.OnAtaque;
            @Parry.started += instance.OnParry;
            @Parry.performed += instance.OnParry;
            @Parry.canceled += instance.OnParry;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IControlesInGameActions instance)
        {
            @Movimiento.started -= instance.OnMovimiento;
            @Movimiento.performed -= instance.OnMovimiento;
            @Movimiento.canceled -= instance.OnMovimiento;
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Ledge.started -= instance.OnLedge;
            @Ledge.performed -= instance.OnLedge;
            @Ledge.canceled -= instance.OnLedge;
            @Climb.started -= instance.OnClimb;
            @Climb.performed -= instance.OnClimb;
            @Climb.canceled -= instance.OnClimb;
            @Ataque.started -= instance.OnAtaque;
            @Ataque.performed -= instance.OnAtaque;
            @Ataque.canceled -= instance.OnAtaque;
            @Parry.started -= instance.OnParry;
            @Parry.performed -= instance.OnParry;
            @Parry.canceled -= instance.OnParry;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IControlesInGameActions instance)
        {
            if (m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlesInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlesInGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlesInGameActions @ControlesInGame => new ControlesInGameActions(this);

    // ControlesInMenu
    private readonly InputActionMap m_ControlesInMenu;
    private List<IControlesInMenuActions> m_ControlesInMenuActionsCallbackInterfaces = new List<IControlesInMenuActions>();
    private readonly InputAction m_ControlesInMenu_NavegarMenu;
    private readonly InputAction m_ControlesInMenu_Seleccionar;
    private readonly InputAction m_ControlesInMenu_Atras;
    private readonly InputAction m_ControlesInMenu_Pestanyas;
    public struct ControlesInMenuActions
    {
        private @ControlJuego m_Wrapper;
        public ControlesInMenuActions(@ControlJuego wrapper) { m_Wrapper = wrapper; }
        public InputAction @NavegarMenu => m_Wrapper.m_ControlesInMenu_NavegarMenu;
        public InputAction @Seleccionar => m_Wrapper.m_ControlesInMenu_Seleccionar;
        public InputAction @Atras => m_Wrapper.m_ControlesInMenu_Atras;
        public InputAction @Pestanyas => m_Wrapper.m_ControlesInMenu_Pestanyas;
        public InputActionMap Get() { return m_Wrapper.m_ControlesInMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlesInMenuActions set) { return set.Get(); }
        public void AddCallbacks(IControlesInMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlesInMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlesInMenuActionsCallbackInterfaces.Add(instance);
            @NavegarMenu.started += instance.OnNavegarMenu;
            @NavegarMenu.performed += instance.OnNavegarMenu;
            @NavegarMenu.canceled += instance.OnNavegarMenu;
            @Seleccionar.started += instance.OnSeleccionar;
            @Seleccionar.performed += instance.OnSeleccionar;
            @Seleccionar.canceled += instance.OnSeleccionar;
            @Atras.started += instance.OnAtras;
            @Atras.performed += instance.OnAtras;
            @Atras.canceled += instance.OnAtras;
            @Pestanyas.started += instance.OnPestanyas;
            @Pestanyas.performed += instance.OnPestanyas;
            @Pestanyas.canceled += instance.OnPestanyas;
        }

        private void UnregisterCallbacks(IControlesInMenuActions instance)
        {
            @NavegarMenu.started -= instance.OnNavegarMenu;
            @NavegarMenu.performed -= instance.OnNavegarMenu;
            @NavegarMenu.canceled -= instance.OnNavegarMenu;
            @Seleccionar.started -= instance.OnSeleccionar;
            @Seleccionar.performed -= instance.OnSeleccionar;
            @Seleccionar.canceled -= instance.OnSeleccionar;
            @Atras.started -= instance.OnAtras;
            @Atras.performed -= instance.OnAtras;
            @Atras.canceled -= instance.OnAtras;
            @Pestanyas.started -= instance.OnPestanyas;
            @Pestanyas.performed -= instance.OnPestanyas;
            @Pestanyas.canceled -= instance.OnPestanyas;
        }

        public void RemoveCallbacks(IControlesInMenuActions instance)
        {
            if (m_Wrapper.m_ControlesInMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlesInMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlesInMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlesInMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlesInMenuActions @ControlesInMenu => new ControlesInMenuActions(this);
    public interface IControlesInGameActions
    {
        void OnMovimiento(InputAction.CallbackContext context);
        void OnSaltar(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnLedge(InputAction.CallbackContext context);
        void OnClimb(InputAction.CallbackContext context);
        void OnAtaque(InputAction.CallbackContext context);
        void OnParry(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IControlesInMenuActions
    {
        void OnNavegarMenu(InputAction.CallbackContext context);
        void OnSeleccionar(InputAction.CallbackContext context);
        void OnAtras(InputAction.CallbackContext context);
        void OnPestanyas(InputAction.CallbackContext context);
    }
}
