//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/ControlJuego.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlJuego: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlJuego()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlJuego"",
    ""maps"": [
        {
            ""name"": ""ControlesInGame"",
            ""id"": ""fd663fba-a09a-4152-9556-54ddfb09510f"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""Value"",
                    ""id"": ""faf49f59-05c2-4da9-9ad4-21332e49b55d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""a9edd0dd-839a-4a12-aa02-fbd469ce45b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""c614f072-63fd-4985-9059-c5bb4299bfe7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ledge"",
                    ""type"": ""Value"",
                    ""id"": ""75008cd7-1d0b-4101-a23b-1d5c2cd2285b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Climb"",
                    ""type"": ""Value"",
                    ""id"": ""60e204cb-e282-4916-952f-bf78c4ae2883"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Ataque"",
                    ""type"": ""Button"",
                    ""id"": ""26b8ae8d-377f-4e02-baaa-f8784087820b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heal"",
                    ""type"": ""Button"",
                    ""id"": ""7baf763b-65ae-438e-b5ff-3763443c7210"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Disparar"",
                    ""type"": ""Button"",
                    ""id"": ""c9abc525-b4a2-4593-a724-1361459a8fea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4eed1fd4-1684-4591-bc89-930ae0fb094d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbrirMenu"",
                    ""type"": ""Button"",
                    ""id"": ""3383543e-334f-4376-9e52-49eb3d85de0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ba32abfc-e128-400a-908b-3b273c052640"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""faefe881-20bc-4f01-ba4b-16326e072ed0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""119cea59-1f61-4c06-b0eb-4564d51a2699"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""275b6cec-3a8a-49b1-a68a-7182a97c266a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a34bf21-194d-4171-b72e-df96975b5bf1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1d65721f-ea43-4352-befb-59102ad0bce3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""477e1db8-50b8-4e8f-bd98-e722b910cb79"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f5535bf5-6121-4fd1-96f5-50f2cd4719b0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e23b2fac-1348-4e96-863f-67eef3b7d3bb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""72eaae6c-3a8d-4180-ab16-246161521188"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5c9fc383-6738-4108-a3cb-dbf990d1570a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""74ea0f8c-95b5-484b-bf72-4fd35465fc3f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb8f48a8-ea39-4ff3-989d-1aac14297dbb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b6b9613b-7586-4e29-96ee-74f977965c1c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3bde9120-3c6b-4d1e-bd50-5959561ae8fd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6f04ad7e-8bac-4ae2-9c0b-f1658d61447c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""354d2a00-80a0-4dea-bc7f-05f52d28d83b"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ataque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2babb7b-4751-4442-93e9-7f9c7092a43b"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f294577-1643-4ddc-930d-01f3fb0baa4e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38f0989f-fabe-4993-b827-0cd71f4e6d6d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7071bc12-c489-4c13-8d7d-3b173be047eb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbrirMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // ControlesInGame
        m_ControlesInGame = asset.FindActionMap("ControlesInGame", throwIfNotFound: true);
        m_ControlesInGame_Movimiento = m_ControlesInGame.FindAction("Movimiento", throwIfNotFound: true);
        m_ControlesInGame_Saltar = m_ControlesInGame.FindAction("Saltar", throwIfNotFound: true);
        m_ControlesInGame_Dash = m_ControlesInGame.FindAction("Dash", throwIfNotFound: true);
        m_ControlesInGame_Ledge = m_ControlesInGame.FindAction("Ledge", throwIfNotFound: true);
        m_ControlesInGame_Climb = m_ControlesInGame.FindAction("Climb", throwIfNotFound: true);
        m_ControlesInGame_Ataque = m_ControlesInGame.FindAction("Ataque", throwIfNotFound: true);
        m_ControlesInGame_Heal = m_ControlesInGame.FindAction("Heal", throwIfNotFound: true);
        m_ControlesInGame_Disparar = m_ControlesInGame.FindAction("Disparar", throwIfNotFound: true);
        m_ControlesInGame_Interact = m_ControlesInGame.FindAction("Interact", throwIfNotFound: true);
        m_ControlesInGame_AbrirMenu = m_ControlesInGame.FindAction("AbrirMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlesInGame
    private readonly InputActionMap m_ControlesInGame;
    private List<IControlesInGameActions> m_ControlesInGameActionsCallbackInterfaces = new List<IControlesInGameActions>();
    private readonly InputAction m_ControlesInGame_Movimiento;
    private readonly InputAction m_ControlesInGame_Saltar;
    private readonly InputAction m_ControlesInGame_Dash;
    private readonly InputAction m_ControlesInGame_Ledge;
    private readonly InputAction m_ControlesInGame_Climb;
    private readonly InputAction m_ControlesInGame_Ataque;
    private readonly InputAction m_ControlesInGame_Heal;
    private readonly InputAction m_ControlesInGame_Disparar;
    private readonly InputAction m_ControlesInGame_Interact;
    private readonly InputAction m_ControlesInGame_AbrirMenu;
    public struct ControlesInGameActions
    {
        private @ControlJuego m_Wrapper;
        public ControlesInGameActions(@ControlJuego wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimiento => m_Wrapper.m_ControlesInGame_Movimiento;
        public InputAction @Saltar => m_Wrapper.m_ControlesInGame_Saltar;
        public InputAction @Dash => m_Wrapper.m_ControlesInGame_Dash;
        public InputAction @Ledge => m_Wrapper.m_ControlesInGame_Ledge;
        public InputAction @Climb => m_Wrapper.m_ControlesInGame_Climb;
        public InputAction @Ataque => m_Wrapper.m_ControlesInGame_Ataque;
        public InputAction @Heal => m_Wrapper.m_ControlesInGame_Heal;
        public InputAction @Disparar => m_Wrapper.m_ControlesInGame_Disparar;
        public InputAction @Interact => m_Wrapper.m_ControlesInGame_Interact;
        public InputAction @AbrirMenu => m_Wrapper.m_ControlesInGame_AbrirMenu;
        public InputActionMap Get() { return m_Wrapper.m_ControlesInGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlesInGameActions set) { return set.Get(); }
        public void AddCallbacks(IControlesInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Add(instance);
            @Movimiento.started += instance.OnMovimiento;
            @Movimiento.performed += instance.OnMovimiento;
            @Movimiento.canceled += instance.OnMovimiento;
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Ledge.started += instance.OnLedge;
            @Ledge.performed += instance.OnLedge;
            @Ledge.canceled += instance.OnLedge;
            @Climb.started += instance.OnClimb;
            @Climb.performed += instance.OnClimb;
            @Climb.canceled += instance.OnClimb;
            @Ataque.started += instance.OnAtaque;
            @Ataque.performed += instance.OnAtaque;
            @Ataque.canceled += instance.OnAtaque;
            @Heal.started += instance.OnHeal;
            @Heal.performed += instance.OnHeal;
            @Heal.canceled += instance.OnHeal;
            @Disparar.started += instance.OnDisparar;
            @Disparar.performed += instance.OnDisparar;
            @Disparar.canceled += instance.OnDisparar;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @AbrirMenu.started += instance.OnAbrirMenu;
            @AbrirMenu.performed += instance.OnAbrirMenu;
            @AbrirMenu.canceled += instance.OnAbrirMenu;
        }

        private void UnregisterCallbacks(IControlesInGameActions instance)
        {
            @Movimiento.started -= instance.OnMovimiento;
            @Movimiento.performed -= instance.OnMovimiento;
            @Movimiento.canceled -= instance.OnMovimiento;
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Ledge.started -= instance.OnLedge;
            @Ledge.performed -= instance.OnLedge;
            @Ledge.canceled -= instance.OnLedge;
            @Climb.started -= instance.OnClimb;
            @Climb.performed -= instance.OnClimb;
            @Climb.canceled -= instance.OnClimb;
            @Ataque.started -= instance.OnAtaque;
            @Ataque.performed -= instance.OnAtaque;
            @Ataque.canceled -= instance.OnAtaque;
            @Heal.started -= instance.OnHeal;
            @Heal.performed -= instance.OnHeal;
            @Heal.canceled -= instance.OnHeal;
            @Disparar.started -= instance.OnDisparar;
            @Disparar.performed -= instance.OnDisparar;
            @Disparar.canceled -= instance.OnDisparar;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @AbrirMenu.started -= instance.OnAbrirMenu;
            @AbrirMenu.performed -= instance.OnAbrirMenu;
            @AbrirMenu.canceled -= instance.OnAbrirMenu;
        }

        public void RemoveCallbacks(IControlesInGameActions instance)
        {
            if (m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlesInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlesInGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlesInGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlesInGameActions @ControlesInGame => new ControlesInGameActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IControlesInGameActions
    {
        void OnMovimiento(InputAction.CallbackContext context);
        void OnSaltar(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnLedge(InputAction.CallbackContext context);
        void OnClimb(InputAction.CallbackContext context);
        void OnAtaque(InputAction.CallbackContext context);
        void OnHeal(InputAction.CallbackContext context);
        void OnDisparar(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAbrirMenu(InputAction.CallbackContext context);
    }
}
